const crypto=require('crypto');
const {getProductMap,calculateOrder}=require('./catalog');
const {getLocalDeliverySettings,isEligibleAddress}=require('./local-delivery');
const {evaluate:evalPromotion,recordUsage:recordPromotionUsage}=require('./promotions');
const {getBankTransferSettings,isConfigured:bankTransferConfigured,publicDetails:bankTransferPublicDetails}=require('./bank-transfer');
const persistence=require('./persistence');
const db=require('./database');

function cleanText(value,max=180){return String(value||'').trim().slice(0,max)}
function cleanTrackingUrl(value){
  const raw=cleanText(value,500);if(!raw)return '';
  try{const url=new URL(raw);if(!['http:','https:'].includes(url.protocol))return '';return url.toString()}catch{return ''}
}
function shipmentFor(order={}){const shipment=order.shipment||{};return {carrier:cleanText(shipment.carrier,100),trackingNumber:cleanText(shipment.trackingNumber,120),trackingUrl:cleanTrackingUrl(shipment.trackingUrl),shippedAt:shipment.shippedAt||'',deliveredAt:shipment.deliveredAt||''}}
function statusHistoryFor(order={}){
  const raw=Array.isArray(order.statusHistory)?order.statusHistory:[],seen=[];
  for(const item of raw){const status=cleanText(item?.status,40),at=cleanText(item?.at,80);if(status&&at)seen.push({status,at,...(item?.reason?{reason:cleanText(item.reason,180)}:{})})}
  if(!seen.length&&order.status&&order.createdAt)seen.push({status:order.status,at:order.createdAt});return seen;
}
function sanitizeCheckout(raw={}){const keys=['nombre','apellidos','email','telefono','calle','colonia','cp','ciudad','estado','pais','nota','deliveryMethod'];const out={};for(const k of keys)out[k]=cleanText(raw[k],k==='nota'?500:(k==='calle'?240:180));return out}
function normalizeItems(items=[]){return (Array.isArray(items)?items:[]).map(item=>({id:cleanText(item.id,80),qty:Math.max(1,Math.min(20,Number.parseInt(item.qty,10)||1)),color:cleanText(item.color,60),size:cleanText(item.size,20)}))}
function itemDetails(items=[]){return normalizeItems(items).map(item=>{const product=getProductMap()[item.id];if(!product)throw new Error('Producto no válido.');return {...item,name:product.name,unitPrice:product.price,lineTotal:product.price*item.qty}})}
function restoreItemsIntoInventory(inventory,items=[]){for(const item of normalizeItems(items)){if(!inventory[item.id])inventory[item.id]={};if(!inventory[item.id][item.color])inventory[item.id][item.color]={};const current=Number(inventory[item.id][item.color][item.size]);inventory[item.id][item.color][item.size]=(Number.isFinite(current)?Math.max(0,current):0)+item.qty}}

async function inventoryFor(items=[],client=null,{skipRelease=false}={}){
  if(!skipRelease&&!client)await releaseExpiredReservations();
  const inventory=await persistence.getInventory(client,{forUpdate:!!client});
  for(const item of normalizeItems(items)){
    const stock=inventory?.[item.id]?.[item.color]?.[item.size];
    if(!Number.isFinite(stock))throw new Error(`Inventario no configurado para ${item.id} / ${item.color} / ${item.size}.`);
    if(stock<item.qty)throw new Error(`Inventario insuficiente para ${item.id} / ${item.color} / ${item.size}.`);
  }
  return inventory;
}
async function decrementInventory(items=[],client=null){const inventory=await inventoryFor(items,client,{skipRelease:true});for(const item of normalizeItems(items))inventory[item.id][item.color][item.size]-=item.qty;await persistence.saveInventory(inventory,client);return inventory}
async function incrementInventory(items=[],client=null){const inventory=await persistence.getInventory(client,{forUpdate:!!client});restoreItemsIntoInventory(inventory,items);await persistence.saveInventory(inventory,client);return inventory}

async function releaseExpiredReservations(nowMs=Date.now()){
  return db.withTransaction(async client=>{
    const orders=await persistence.getOrders(client,{forUpdate:!!client});if(!orders.length)return 0;
    let inventory=null,released=0;const changed=[];const nowIso=new Date(nowMs).toISOString();
    for(const order of orders){
      if(!order||order.status==='Cancelado'||order.paymentStatus==='Pagado')continue;
      let shouldRelease=false,marker=null;
      if(order.paymentMethod==='Transferencia bancaria'){
        const transfer=order.transfer||{};if(transfer.inventoryRestoredAt)continue;
        const expiry=transfer.proof?.uploadedAt?Date.parse(transfer.proofReviewUntil||transfer.expiresAt||''):Date.parse(transfer.expiresAt||'');
        if(Number.isFinite(expiry)&&expiry<=nowMs){shouldRelease=true;marker='transfer'}
      }else if(order.paymentMethod==='Contraentrega'){
        const reservation=order.reservation||{};if(reservation.inventoryRestoredAt||order.status!=='Nuevo')continue;
        const expiry=Date.parse(reservation.expiresAt||'');if(Number.isFinite(expiry)&&expiry<=nowMs){shouldRelease=true;marker='cash'}
      }
      if(!shouldRelease)continue;
      if(!inventory)inventory=await persistence.getInventory(client,{forUpdate:!!client});restoreItemsIntoInventory(inventory,order.items||[]);
      if(marker==='transfer'){if(!order.transfer)order.transfer={reference:order.orderNumber,bank:{}};order.transfer.inventoryRestoredAt=nowIso}else{if(!order.reservation)order.reservation={};order.reservation.inventoryRestoredAt=nowIso}
      order.status='Cancelado';order.paymentStatus='Cancelado';order.updatedAt=nowIso;if(!Array.isArray(order.statusHistory))order.statusHistory=[];order.statusHistory.push({status:'Cancelado',at:nowIso,reason:'Reserva expirada'});changed.push(order);released++;
    }
    if(inventory)await persistence.saveInventory(inventory,client);for(const order of changed)await persistence.updateOrder(order,client);return released;
  });
}
function assertManualOrderAllowance(orders=[],checkout={}){
  const email=cleanText(checkout.email,180).toLowerCase(),phone=cleanText(checkout.telefono,60).replace(/\D+/g,'');if(!email&&!phone)return;
  const cutoff=Date.now()-24*60*60*1000;
  const active=(Array.isArray(orders)?orders:[]).filter(order=>{if(!['Transferencia bancaria','Contraentrega'].includes(order?.paymentMethod))return false;if(['Cancelado','Entregado'].includes(order?.status)||order?.paymentStatus==='Pagado')return false;const created=Date.parse(order?.createdAt||'');if(!Number.isFinite(created)||created<cutoff)return false;const orderEmail=cleanText(order?.customer?.email,180).toLowerCase(),orderPhone=cleanText(order?.customer?.telefono,60).replace(/\D+/g,'');return (email&&orderEmail===email)||(phone&&orderPhone===phone)});
  if(active.length>=4)throw new Error('Ya existen varios pedidos pendientes con estos datos. Completa o cancela uno antes de crear otro.');
}
async function saveDraft(paymentIntentId,data={}){return persistence.saveDraft(paymentIntentId,data)}
async function getDraft(paymentIntentId){return persistence.getDraft(paymentIntentId)}
function nextOrderNumber(orders){const used=new Set((Array.isArray(orders)?orders:[]).map(o=>String(o.orderNumber||'').trim().toUpperCase()));for(let attempt=0;attempt<100;attempt++){const candidate='NR-'+String(crypto.randomInt(10000000,100000000));if(!used.has(candidate))return candidate}throw new Error('No fue posible generar un número de pedido único. Intenta nuevamente.')}
function publicTransfer(order={}){const transfer=order.transfer||{},bank=transfer.bank||{},proof=transfer.proof||null;return {reference:cleanText(transfer.reference||order.orderNumber,60),expiresAt:cleanText(transfer.expiresAt,80),paidAt:cleanText(transfer.paidAt,80),bank:{bankName:cleanText(bank.bankName,100),accountHolder:cleanText(bank.accountHolder,160),clabe:cleanText(bank.clabe,18),accountNumber:cleanText(bank.accountNumber,30),cardNumber:cleanText(bank.cardNumber,19),paymentDeadlineHours:Number(bank.paymentDeadlineHours)||24,proofUploadEnabled:bank.proofUploadEnabled!==false,instructions:cleanText(bank.instructions,900)},proof:proof?{originalName:cleanText(proof.originalName,180),mimeType:cleanText(proof.mimeType,100),size:Number(proof.size)||0,uploadedAt:cleanText(proof.uploadedAt,80)}:null}}
function publicOrder(order){return {orderNumber:order.orderNumber,status:order.status,paymentStatus:order.paymentStatus,paymentMethod:order.paymentMethod,deliveryMethod:order.deliveryMethod||'Envío nacional',createdAt:order.createdAt,updatedAt:order.updatedAt||'',customer:order.customer,note:order.note||'',promoCode:order.promoCode||'',promotion:order.promotion||null,items:(order.items||[]).map(i=>({...i,unitPrice:i.unitPrice/100,lineTotal:i.lineTotal/100})),totals:{subtotal:order.totals.subtotal/100,discount:order.totals.discount/100,shipping:order.totals.shipping/100,total:order.totals.total/100},transfer:order.paymentMethod==='Transferencia bancaria'?publicTransfer(order):null,shipment:shipmentFor(order),statusHistory:statusHistoryFor(order)}}
async function calculateCheckoutTotals(items=[],promoCode='',checkout={},client=null){const base=calculateOrder(items,'');let shipping=base.shipping;if(String(checkout?.deliveryMethod||'')==='local'){const settings=getLocalDeliverySettings();if(!isEligibleAddress(checkout,settings))throw new Error('La dirección no es elegible para entrega local.');shipping=Math.round(Number(settings.fee||0)*100)}const result=await evalPromotion({items,promoCode,customerEmail:checkout?.email||'',shippingCents:shipping,client});if(!result.ok)throw new Error(result.error||'El código promocional no es válido.');return {subtotal:result.subtotal,discount:result.discount,shipping:result.shipping,total:result.total,promotion:result.promotion}}

async function createLocalCashOrder(data={},customerId=''){
  const settings=getLocalDeliverySettings();if(!settings.enabled||!settings.cashOnDelivery)throw new Error('El pago contraentrega no está disponible.');
  const checkout=sanitizeCheckout(data.checkout||{});checkout.deliveryMethod='local';if(!isEligibleAddress(checkout,settings))throw new Error('La dirección no es elegible para entrega local y pago contraentrega.');
  const items=normalizeItems(data.items);if(!items.length)throw new Error('El carrito está vacío.');await releaseExpiredReservations();
  return db.withTransaction(async client=>{
    const orders=await persistence.getOrders(client,{forUpdate:!!client});await inventoryFor(items,client,{skipRelease:true});const requestId=cleanText(data.requestId,100);
    if(requestId){const existing=orders.find(o=>o.clientRequestId===requestId);if(existing)return publicOrder(existing)}
    assertManualOrderAllowance(orders,checkout);const totals=await calculateCheckoutTotals(items,data.promoCode||'',checkout,client);await decrementInventory(items,client);
    const now=new Date().toISOString(),codHours=Math.max(1,Math.min(168,Number(process.env.COD_RESERVATION_HOURS)||48)),reservationExpiresAt=new Date(Date.now()+codHours*60*60*1000).toISOString();const customer={...checkout};delete customer.nota;delete customer.deliveryMethod;
    const order={orderNumber:nextOrderNumber(orders),clientRequestId:requestId,status:'Nuevo',paymentStatus:'Pendiente',paymentMethod:'Contraentrega',deliveryMethod:'Entrega local',createdAt:now,customerId:cleanText(customerId,80),customer,note:cleanText(checkout.nota||'',500),items:itemDetails(items),promoCode:cleanText(data.promoCode||'',40),promotion:totals.promotion||null,totals:{subtotal:totals.subtotal,discount:totals.discount,shipping:totals.shipping,total:totals.total},reservation:{inventoryReservedAt:now,expiresAt:reservationExpiresAt,inventoryRestoredAt:''},shipment:{carrier:'Entrega local',trackingNumber:'',trackingUrl:'',shippedAt:'',deliveredAt:''},statusHistory:[{status:'Nuevo',at:now}]};
    await persistence.insertOrder(order,client);return publicOrder(order);
  });
}
async function createBankTransferOrder(data={},customerId=''){
  const settings=getBankTransferSettings();if(!bankTransferConfigured(settings))throw new Error('La transferencia bancaria no está disponible en este momento.');const checkout=sanitizeCheckout(data.checkout||{}),items=normalizeItems(data.items);if(!items.length)throw new Error('El carrito está vacío.');await releaseExpiredReservations();
  return db.withTransaction(async client=>{
    const orders=await persistence.getOrders(client,{forUpdate:!!client});await inventoryFor(items,client,{skipRelease:true});const requestId=cleanText(data.requestId,100);if(requestId){const existing=orders.find(o=>o.clientRequestId===requestId);if(existing)return publicOrder(existing)}assertManualOrderAllowance(orders,checkout);
    const totals=await calculateCheckoutTotals(items,data.promoCode||'',checkout,client),orderNumber=nextOrderNumber(orders),now=new Date(),expiresAt=new Date(now.getTime()+Math.max(1,Number(settings.paymentDeadlineHours)||24)*60*60*1000).toISOString(),bank=bankTransferPublicDetails(settings);await decrementInventory(items,client);const customer={...checkout};delete customer.nota;delete customer.deliveryMethod;
    const order={orderNumber,clientRequestId:requestId,status:'Pendiente de pago',paymentStatus:'Pendiente',paymentMethod:'Transferencia bancaria',deliveryMethod:String(checkout.deliveryMethod||'')==='local'?'Entrega local':'Envío nacional',createdAt:now.toISOString(),customerId:cleanText(customerId,80),customer,note:cleanText(checkout.nota||'',500),items:itemDetails(items),promoCode:cleanText(data.promoCode||'',40),promotion:totals.promotion||null,totals:{subtotal:totals.subtotal,discount:totals.discount,shipping:totals.shipping,total:totals.total},transfer:{reference:orderNumber,expiresAt,paidAt:'',bank,proof:null,inventoryReservedAt:now.toISOString(),inventoryRestoredAt:''},shipment:{carrier:'',trackingNumber:'',trackingUrl:'',shippedAt:'',deliveredAt:''},statusHistory:[{status:'Pendiente de pago',at:now.toISOString()}]};
    await persistence.insertOrder(order,client);return publicOrder(order);
  });
}
async function saveBankTransferProof(orderNumber,email,proofData={}){
  await releaseExpiredReservations();const normalizedNumber=cleanText(orderNumber,40).toUpperCase(),normalizedEmail=cleanText(email,180).toLowerCase();if(!normalizedNumber||!normalizedEmail)throw new Error('Faltan los datos del pedido.');
  return db.withTransaction(async client=>{const order=await persistence.findOrderByColumn('order_number',normalizedNumber,client,{forUpdate:!!client});if(!order||String(order.customer?.email||'').trim().toLowerCase()!==normalizedEmail)throw new Error('No encontramos el pedido con esos datos.');if(order.paymentMethod!=='Transferencia bancaria')throw new Error('Este pedido no utiliza transferencia bancaria.');if(order.paymentStatus==='Pagado')throw new Error('Este pedido ya está marcado como pagado.');if(order.status==='Cancelado')throw new Error('Este pedido fue cancelado.');if(!order.transfer)order.transfer={reference:order.orderNumber,bank:{}};const uploadedAt=new Date().toISOString(),reviewHours=Math.max(1,Math.min(168,Number(process.env.BANK_PROOF_REVIEW_HOURS)||48));order.transfer.proof={storedName:cleanText(proofData.storedName,200),originalName:cleanText(proofData.originalName,180),mimeType:cleanText(proofData.mimeType,100),size:Math.max(0,Number(proofData.size)||0),uploadedAt};order.transfer.proofReviewUntil=new Date(Date.now()+reviewHours*60*60*1000).toISOString();order.updatedAt=uploadedAt;await persistence.updateOrder(order,client);return {order:publicOrder(order),previousStoredName:cleanText(proofData.previousStoredName,200)}});
}
async function getBankTransferProofMeta(orderNumber){const normalized=cleanText(orderNumber,40).toUpperCase(),order=await persistence.findOrderByColumn('order_number',normalized);if(!order)throw new Error('Pedido no encontrado.');if(order.paymentMethod!=='Transferencia bancaria'||!order.transfer?.proof?.storedName)throw new Error('Este pedido no tiene comprobante.');return {...order.transfer.proof}}
async function markBankTransferPaid(orderNumber){await releaseExpiredReservations();const normalized=cleanText(orderNumber,40).toUpperCase();return db.withTransaction(async client=>{const order=await persistence.findOrderByColumn('order_number',normalized,client,{forUpdate:!!client});if(!order)throw new Error('Pedido no encontrado.');if(order.paymentMethod!=='Transferencia bancaria')throw new Error('Este pedido no utiliza transferencia bancaria.');if(order.status==='Cancelado')throw new Error('No puedes marcar como pagado un pedido cancelado.');const now=new Date().toISOString();if(order.paymentStatus!=='Pagado'){order.paymentStatus='Pagado';order.status='Pagado';order.updatedAt=now;if(!order.transfer)order.transfer={reference:order.orderNumber,bank:{}};order.transfer.paidAt=now;if(!Array.isArray(order.statusHistory))order.statusHistory=[];order.statusHistory.push({status:'Pagado',at:now});await persistence.updateOrder(order,client);await recordPromotionUsage(order.promotion,order.customer?.email||'',order.orderNumber,client)}return adminOrder(order)})}

async function finalizeStripeOrder(stripe,paymentIntentId){
  if(!stripe)throw new Error('Stripe no configurado.');let existing=await persistence.findOrderByColumn('payment_intent_id',paymentIntentId);if(existing)return publicOrder(existing);
  const pi=await stripe.paymentIntents.retrieve(paymentIntentId);if(pi.status!=='succeeded')throw new Error('El pago todavía no está confirmado.');
  return db.withTransaction(async client=>{existing=await persistence.findOrderByColumn('payment_intent_id',paymentIntentId,client,{forUpdate:!!client});if(existing)return publicOrder(existing);const draft=await persistence.getDraft(paymentIntentId,client);if(!draft||!draft.items?.length)throw new Error('No encontramos los datos del pedido asociados a este pago.');const totals=await calculateCheckoutTotals(draft.items,draft.promoCode||'',draft.checkout||{},client);if(totals.total!==pi.amount_received&&totals.total!==pi.amount)throw new Error('El total pagado no coincide con el pedido.');const orders=await persistence.getOrders(client,{forUpdate:!!client}),inventory=await decrementInventory(draft.items,client);const now=new Date().toISOString();const order={orderNumber:nextOrderNumber(orders),paymentIntentId,status:'Pagado',paymentStatus:'Pagado',paymentMethod:'Stripe',deliveryMethod:String(draft.checkout?.deliveryMethod||'')==='local'?'Entrega local':'Envío nacional',createdAt:now,customerId:cleanText(draft.customerId,80),customer:(()=>{const c=sanitizeCheckout(draft.checkout||{});delete c.nota;delete c.deliveryMethod;return c})(),note:cleanText(draft.checkout?.nota||'',500),items:itemDetails(draft.items),promoCode:cleanText(draft.promoCode||'',40),promotion:totals.promotion||null,totals:{subtotal:totals.subtotal,discount:totals.discount,shipping:totals.shipping,total:totals.total},shipment:{carrier:'',trackingNumber:'',trackingUrl:'',shippedAt:'',deliveredAt:''},statusHistory:[{status:'Pagado',at:now}]};await persistence.insertOrder(order,client);await recordPromotionUsage(order.promotion,order.customer?.email||'',order.orderNumber,client);return {...publicOrder(order),inventory}});
}
function paypalAmountCents(paypalOrder={}){const units=Array.isArray(paypalOrder.purchase_units)?paypalOrder.purchase_units:[];for(const unit of units){const captures=Array.isArray(unit?.payments?.captures)?unit.payments.captures:[],completed=captures.find(c=>String(c?.status||'').toUpperCase()==='COMPLETED')||captures[0],value=completed?.amount?.value;if(value!==undefined&&value!==null){const cents=Math.round(Number(value)*100);if(Number.isFinite(cents))return cents}}const cents=Math.round(Number(units[0]?.amount?.value)*100);return Number.isFinite(cents)?cents:0}
async function findOrderByPayPalOrderId(id){const found=await persistence.findOrderByColumn('paypal_order_id',cleanText(id,120));return found?publicOrder(found):null}
async function finalizePayPalOrder(paypalOrder={},paypalOrderId=''){
  const id=cleanText(paypalOrderId||paypalOrder?.id,120);if(!id)throw new Error('Falta el identificador de PayPal.');if(String(paypalOrder?.status||'').toUpperCase()!=='COMPLETED')throw new Error('El pago de PayPal todavía no está completado.');
  return db.withTransaction(async client=>{const existing=await persistence.findOrderByColumn('paypal_order_id',id,client,{forUpdate:!!client});if(existing)return publicOrder(existing);const draft=await persistence.getDraft(`paypal:${id}`,client);if(!draft||!draft.items?.length)throw new Error('No encontramos los datos del pedido asociados a este pago de PayPal.');const totals=await calculateCheckoutTotals(draft.items,draft.promoCode||'',draft.checkout||{},client),paidCents=paypalAmountCents(paypalOrder);if(!paidCents||paidCents!==totals.total)throw new Error('El total pagado en PayPal no coincide con el pedido.');const orders=await persistence.getOrders(client,{forUpdate:!!client}),inventory=await decrementInventory(draft.items,client),units=Array.isArray(paypalOrder.purchase_units)?paypalOrder.purchase_units:[],captures=units.flatMap(u=>Array.isArray(u?.payments?.captures)?u.payments.captures:[]),completedCapture=captures.find(c=>String(c?.status||'').toUpperCase()==='COMPLETED')||captures[0]||{},now=new Date().toISOString();const order={orderNumber:nextOrderNumber(orders),paypalOrderId:id,paypalCaptureId:cleanText(completedCapture.id,120),status:'Pagado',paymentStatus:'Pagado',paymentMethod:'PayPal',deliveryMethod:String(draft.checkout?.deliveryMethod||'')==='local'?'Entrega local':'Envío nacional',createdAt:now,customerId:cleanText(draft.customerId,80),customer:(()=>{const c=sanitizeCheckout(draft.checkout||{});delete c.nota;delete c.deliveryMethod;return c})(),note:cleanText(draft.checkout?.nota||'',500),items:itemDetails(draft.items),promoCode:cleanText(draft.promoCode||'',40),promotion:totals.promotion||null,totals:{subtotal:totals.subtotal,discount:totals.discount,shipping:totals.shipping,total:totals.total},shipment:{carrier:'',trackingNumber:'',trackingUrl:'',shippedAt:'',deliveredAt:''},statusHistory:[{status:'Pagado',at:now}]};await persistence.insertOrder(order,client);await recordPromotionUsage(order.promotion,order.customer?.email||'',order.orderNumber,client);return {...publicOrder(order),inventory}});
}
function mercadoPagoAmountCents(mpOrder={}){const cents=Math.round(Number(mpOrder.total_paid_amount??mpOrder.total_amount)*100);return Number.isFinite(cents)?cents:0}
async function findOrderByMercadoPagoOrderId(id){const found=await persistence.findOrderByColumn('mercado_pago_order_id',cleanText(id,160));return found?publicOrder(found):null}
async function finalizeMercadoPagoOrder(mpOrder={},mercadoPagoOrderId=''){
  const id=cleanText(mercadoPagoOrderId||mpOrder?.id,160);if(!id)throw new Error('Falta el identificador de Mercado Pago.');const status=String(mpOrder?.status||'').toLowerCase(),detail=String(mpOrder?.status_detail||'').toLowerCase();if(status!=='processed'||detail!=='accredited')throw new Error('El pago de Mercado Pago todavía no está acreditado.');
  return db.withTransaction(async client=>{const existing=await persistence.findOrderByColumn('mercado_pago_order_id',id,client,{forUpdate:!!client});if(existing)return publicOrder(existing);const draft=await persistence.getDraft(`mercadopago:${id}`,client);if(!draft||!draft.items?.length)throw new Error('No encontramos los datos del pedido asociados a este pago de Mercado Pago.');const totals=await calculateCheckoutTotals(draft.items,draft.promoCode||'',draft.checkout||{},client),paidCents=mercadoPagoAmountCents(mpOrder);if(!paidCents||paidCents!==totals.total)throw new Error('El total pagado en Mercado Pago no coincide con el pedido.');const orders=await persistence.getOrders(client,{forUpdate:!!client}),inventory=await decrementInventory(draft.items,client),payments=Array.isArray(mpOrder?.transactions?.payments)?mpOrder.transactions.payments:[],accreditedPayment=payments.find(p=>String(p?.status_detail||'').toLowerCase()==='accredited')||payments[0]||{},now=new Date().toISOString();const order={orderNumber:nextOrderNumber(orders),mercadoPagoOrderId:id,mercadoPagoPaymentId:cleanText(accreditedPayment.id,160),status:'Pagado',paymentStatus:'Pagado',paymentMethod:'Mercado Pago',deliveryMethod:String(draft.checkout?.deliveryMethod||'')==='local'?'Entrega local':'Envío nacional',createdAt:now,customerId:cleanText(draft.customerId,80),customer:(()=>{const c=sanitizeCheckout(draft.checkout||{});delete c.nota;delete c.deliveryMethod;return c})(),note:cleanText(draft.checkout?.nota||'',500),items:itemDetails(draft.items),promoCode:cleanText(draft.promoCode||'',40),promotion:totals.promotion||null,totals:{subtotal:totals.subtotal,discount:totals.discount,shipping:totals.shipping,total:totals.total},shipment:{carrier:'',trackingNumber:'',trackingUrl:'',shippedAt:'',deliveredAt:''},statusHistory:[{status:'Pagado',at:now}]};await persistence.insertOrder(order,client);await recordPromotionUsage(order.promotion,order.customer?.email||'',order.orderNumber,client);return {...publicOrder(order),inventory}});
}
async function findOrderByMercadoPagoPaymentId(id){const found=await persistence.findOrderByColumn('mercado_pago_payment_id',cleanText(id,160));return found?publicOrder(found):null}
async function finalizeMercadoPagoPayment(mpPayment={},externalReference=''){
  const paymentId=cleanText(mpPayment?.id,160);if(!paymentId)throw new Error('Falta el identificador del pago de Mercado Pago.');if(String(mpPayment?.status||'').toLowerCase()!=='approved')throw new Error('El pago de Mercado Pago todavía no está aprobado.');const reference=cleanText(externalReference||mpPayment?.external_reference,160);if(!reference)throw new Error('El pago de Mercado Pago no contiene la referencia del pedido.');
  return db.withTransaction(async client=>{const existing=await persistence.findOrderByColumn('mercado_pago_payment_id',paymentId,client,{forUpdate:!!client});if(existing)return publicOrder(existing);const draft=await persistence.getDraft(`mercadopago-reference:${reference}`,client);if(!draft||!draft.items?.length)throw new Error('No encontramos los datos del pedido asociados a este pago de Mercado Pago.');const totals=await calculateCheckoutTotals(draft.items,draft.promoCode||'',draft.checkout||{},client),paidCents=Math.round(Number(mpPayment?.transaction_amount)*100);if(!Number.isFinite(paidCents)||!paidCents||paidCents!==totals.total)throw new Error('El total pagado en Mercado Pago no coincide con el pedido.');const orders=await persistence.getOrders(client,{forUpdate:!!client}),inventory=await decrementInventory(draft.items,client),now=new Date().toISOString();const order={orderNumber:nextOrderNumber(orders),mercadoPagoOrderId:cleanText(draft.mercadoPagoPreferenceId||'',160),mercadoPagoPreferenceId:cleanText(draft.mercadoPagoPreferenceId||'',160),mercadoPagoPaymentId:paymentId,status:'Pagado',paymentStatus:'Pagado',paymentMethod:'Mercado Pago',deliveryMethod:String(draft.checkout?.deliveryMethod||'')==='local'?'Entrega local':'Envío nacional',createdAt:now,customerId:cleanText(draft.customerId,80),customer:(()=>{const c=sanitizeCheckout(draft.checkout||{});delete c.nota;delete c.deliveryMethod;return c})(),note:cleanText(draft.checkout?.nota||'',500),items:itemDetails(draft.items),promoCode:cleanText(draft.promoCode||'',40),promotion:totals.promotion||null,totals:{subtotal:totals.subtotal,discount:totals.discount,shipping:totals.shipping,total:totals.total},shipment:{carrier:'',trackingNumber:'',trackingUrl:'',shippedAt:'',deliveredAt:''},statusHistory:[{status:'Pagado',at:now}]};await persistence.insertOrder(order,client);await recordPromotionUsage(order.promotion,order.customer?.email||'',order.orderNumber,client);return {...publicOrder(order),inventory}});
}

async function getInventory(){await releaseExpiredReservations();return persistence.getInventory()}
function adminOrder(order){return {orderNumber:order.orderNumber,status:order.status,paymentStatus:order.paymentStatus,paymentMethod:order.paymentMethod,deliveryMethod:order.deliveryMethod||'Envío nacional',createdAt:order.createdAt,updatedAt:order.updatedAt||'',customer:order.customer||{},note:order.note||'',items:(order.items||[]).map(i=>({...i,unitPrice:i.unitPrice/100,lineTotal:i.lineTotal/100})),promoCode:order.promoCode||'',promotion:order.promotion||null,totals:{subtotal:order.totals.subtotal/100,discount:order.totals.discount/100,shipping:order.totals.shipping/100,total:order.totals.total/100},transfer:order.paymentMethod==='Transferencia bancaria'?publicTransfer(order):null,shipment:shipmentFor(order),statusHistory:statusHistoryFor(order)}}
async function listOrders(){await releaseExpiredReservations();return (await persistence.getOrders()).slice().reverse().map(adminOrder)}
const ADMIN_ORDER_STATUSES=['Pendiente de pago','Nuevo','Pagado','Preparando','Enviado','Entregado','Cancelado'];
async function updateOrderStatus(orderNumber,status){
  await releaseExpiredReservations();const normalized=cleanText(orderNumber,40).toUpperCase(),next=cleanText(status,40);if(!ADMIN_ORDER_STATUSES.includes(next))throw new Error('Estado de pedido no permitido.');
  return db.withTransaction(async client=>{const order=await persistence.findOrderByColumn('order_number',normalized,client,{forUpdate:!!client});if(!order)throw new Error('Pedido no encontrado.');const now=new Date().toISOString();if(order.status==='Cancelado'&&next!=='Cancelado')throw new Error('Un pedido cancelado no puede reactivarse automáticamente.');if(order.paymentMethod==='Transferencia bancaria'&&order.paymentStatus!=='Pagado'&&next==='Pagado')throw new Error('Usa el botón “Marcar como pagado” para confirmar una transferencia.');if(order.status!==next){if(next==='Cancelado'&&order.paymentStatus!=='Pagado'){if(order.paymentMethod==='Transferencia bancaria'&&!order.transfer?.inventoryRestoredAt){await incrementInventory(order.items||[],client);if(!order.transfer)order.transfer={reference:order.orderNumber,bank:{}};order.transfer.inventoryRestoredAt=now;order.paymentStatus='Cancelado'}else if(order.paymentMethod==='Contraentrega'&&!order.reservation?.inventoryRestoredAt){await incrementInventory(order.items||[],client);if(!order.reservation)order.reservation={};order.reservation.inventoryRestoredAt=now;order.paymentStatus='Cancelado'}}order.status=next;order.updatedAt=now;if(!Array.isArray(order.statusHistory))order.statusHistory=[];order.statusHistory.push({status:next,at:now});if(!order.shipment)order.shipment={};if(next==='Enviado'&&!order.shipment.shippedAt)order.shipment.shippedAt=now;if(next==='Entregado'&&!order.shipment.deliveredAt)order.shipment.deliveredAt=now;if(next==='Entregado'&&order.paymentMethod==='Contraentrega'){order.paymentStatus='Pagado';await recordPromotionUsage(order.promotion,order.customer?.email||'',order.orderNumber,client)}await persistence.updateOrder(order,client)}return adminOrder(order)});
}
async function updateOrderShipment(orderNumber,data={}){const normalized=cleanText(orderNumber,40).toUpperCase();return db.withTransaction(async client=>{const order=await persistence.findOrderByColumn('order_number',normalized,client,{forUpdate:!!client});if(!order)throw new Error('Pedido no encontrado.');if(!order.shipment)order.shipment={};order.shipment.carrier=cleanText(data.carrier,100);order.shipment.trackingNumber=cleanText(data.trackingNumber,120);order.shipment.trackingUrl=cleanTrackingUrl(data.trackingUrl);order.updatedAt=new Date().toISOString();await persistence.updateOrder(order,client);return adminOrder(order)})}
async function setInventoryStock(productId,color,size,qty){const id=cleanText(productId,80),c=cleanText(color,60),s=cleanText(size,20),quantity=Number.parseInt(qty,10);if(!getProductMap()[id])throw new Error('Producto no válido.');if(!c||!s)throw new Error('Color y talla son obligatorios.');if(!Number.isInteger(quantity)||quantity<0||quantity>9999)throw new Error('Cantidad de inventario no válida.');return db.withTransaction(async client=>{const inventory=await persistence.getInventory(client,{forUpdate:!!client});if(!inventory[id]||!inventory[id][c]||!Object.prototype.hasOwnProperty.call(inventory[id][c],s))throw new Error('Variante de inventario no encontrada.');inventory[id][c][s]=quantity;await persistence.saveInventory(inventory,client);return inventory})}
async function reconcileInventoryForProduct(product){return db.withTransaction(async client=>{const inventory=await persistence.getInventory(client,{forUpdate:!!client}),old=inventory[product.id]||{},next={};for(const color of product.colors||[]){next[color]={};for(const size of product.sizes||[]){const existing=old?.[color]?.[size];next[color][size]=Number.isFinite(existing)?Math.max(0,Number(existing)):0}}return persistence.replaceProductInventory(product.id,next,client)})}
async function initializeInventoryForProduct(product,qty=0){const quantity=Number.parseInt(qty,10);if(!Number.isInteger(quantity)||quantity<0||quantity>9999)throw new Error('Cantidad inicial de inventario no válida.');const next={};for(const color of product.colors||[]){next[color]={};for(const size of product.sizes||[])next[color][size]=quantity}return db.withTransaction(client=>persistence.replaceProductInventory(product.id,next,client))}
async function inventorySummary(){const inventory=await getInventory(),variants=[];let totalUnits=0,outOfStock=0,lowStock=0;for(const [productId,colors] of Object.entries(inventory)){for(const [color,sizes] of Object.entries(colors||{})){for(const [size,rawQty] of Object.entries(sizes||{})){const qty=Math.max(0,Number(rawQty)||0);totalUnits+=qty;if(qty===0)outOfStock++;else if(qty<=2)lowStock++;variants.push({productId,color,size,qty})}}}return {inventory,variants,totalUnits,outOfStock,lowStock}}
async function adminSummary(){await releaseExpiredReservations();const orders=await persistence.getOrders(),paidOrders=orders.filter(o=>o.paymentStatus==='Pagado'),revenue=paidOrders.reduce((sum,o)=>sum+Number(o.totals?.total||0),0)/100,preparing=orders.filter(o=>o.status==='Preparando').length,shipped=orders.filter(o=>o.status==='Enviado').length,inventory=await inventorySummary();return {orders:orders.length,paidOrders:paidOrders.length,revenue,preparing,shipped,totalUnits:inventory.totalUnits,outOfStock:inventory.outOfStock,lowStock:inventory.lowStock}}
async function listCustomerOrders(customerId){await releaseExpiredReservations();const id=cleanText(customerId,80);if(!id)return [];return (await persistence.getOrders()).filter(order=>String(order.customerId||'')===id).slice().reverse().map(publicOrder)}
async function findOrder(orderNumber,email=''){await releaseExpiredReservations();const normalizedNumber=String(orderNumber||'').trim().toUpperCase(),normalizedEmail=String(email||'').trim().toLowerCase();if(!normalizedNumber||!normalizedEmail)return null;const order=await persistence.findOrderByColumn('order_number',normalizedNumber);if(!order||String(order.customer?.email||'').trim().toLowerCase()!==normalizedEmail)return null;return publicOrder(order)}

module.exports={sanitizeCheckout,normalizeItems,inventoryFor,saveDraft,getDraft,calculateCheckoutTotals,createLocalCashOrder,createBankTransferOrder,saveBankTransferProof,getBankTransferProofMeta,markBankTransferPaid,finalizeStripeOrder,finalizePayPalOrder,findOrderByPayPalOrderId,finalizeMercadoPagoOrder,findOrderByMercadoPagoOrderId,finalizeMercadoPagoPayment,findOrderByMercadoPagoPaymentId,getInventory,findOrder,listOrders,listCustomerOrders,updateOrderStatus,updateOrderShipment,setInventoryStock,reconcileInventoryForProduct,initializeInventoryForProduct,inventorySummary,adminSummary,releaseExpiredReservations,ADMIN_ORDER_STATUSES};
